//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPractice.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Services
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int service_id { get; set; }
        public int dicount_id { get; set; }
        public double final_price { get; set; }
        public double client_bonus { get; set; }
        public int master_id { get; set; }
        public int reception_id { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual Discounts Discounts { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
    }
}
